# bitbucket-pipelines.yml

pipelines:
  default:
    - step:
        name: Configure SSH and Clone Repository
        image: atlassian/default-image:2
        script:
          - git clone --bare git@bitbucket.org:Boyapati-Venkat/abot-cloud-infra.git
          - cd abot-cloud-infra
          - git push --mirror https://github.com/Boyapati-Venkat/Sync-From-BitBucket.git
