pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:Boyapati-Venkat/abot-cloud-infra.git
          - cd abot-cloud-infra
          - git push --mirror git@github.com:RepoOrg/RepoName.git
          
          
