pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare https://Boyapati-Venkat@bitbucket.org/Boyapati-Venkat/abot-cloud-infra.git
          - cd RepoName.git
          - git push --mirror https://github.com/Boyapati-Venkat/terraform-jenkins-ec2.git
          
          
