# bitbucket-pipelines.yml

pipelines:
  default:
    - step:
        name: Configure SSH and Clone Repository
        image: alpine/git:latest
        script:
          - git clone --bare git@bitbucket.org:Boyapati-Venkat/abot-cloud-infra.git
          - cd abot-cloud-infra.git
          - eval "$(ssh-agent -s)"
          - ssh-add /opt/atlassian/pipelines/agent/ssh/id_rsa
          - cd /opt/atlassian/pipelines/agent/ssh/
          - ls -la
          - cd ~/.ssh
          - ls -la
          - cat config
          - git push --mirror git@github.com:Boyapati-Venkat/Sync-From-BitBucket.git
